<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NivalisOrderFix</AssemblyName>
    <Version>1.1.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>$(GameDir)\BepInEx\core\MonoMod.RuntimeDetour.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <ProjectReference Include="..\NivalisModKit\NivalisModKit.csproj" Private="false" />
  </ItemGroup>
</Project>